### PR TITLE
Process output no longer stored in memory

### LINKED ISSUE #82: [BUG] excessive memory and CPU usage with large outputs
I'm using pueue to queue up some large file copies -- and it's pretty nice!

However I notice after a while, it's taking several seconds of pueued CPU time to `pueue add date` a new task. I would have expected it's just adding it to some kind of in-memory or on-disk queue, and the time should be proportional to the fairly short command line.

I also see `pueued` seems to be using a lot of memory for what it's doing:

```
  PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND 
16885 pts/11   SNl+   2:54     71  1930 1043077 779556 13.3 pueued
```

I don't know how to reproduce it, but maybe it's connected to some of these commands producing a lot of output? Ideally it would just stay on files on disk and not be in memory.

This is pueue 0.3.1 from Cargo, on Debian Buster.

### PR DESCRIPTION
**Pull request by Nukesor**
Resolves #82

### CODE REVIEW

File: client/output.rs [hunk 1]
```diff
@@ -171,48 +171,51 @@ pub fn print_logs(tasks: BTreeMap<usize, Task>, cli_command: &SubCommand) {
...
     if json {
-        println!("{}", serde_json::to_string(&tasks).unwrap());
+        println!("{}", serde_json::to_string(&task_logs).unwrap());
         return;
     }
 
-    if task_ids.is_empty() && tasks.is_empty() {
-        println!("There are no finished tasks");
+    if task_ids.is_empty() && task_logs.is_empty() {
+        println!("There are no finished task_logs");
```
[the remark this answers is not in the document]
Comment (Nukesor) [reply client/output.rs]: Nice catch. Search and replace did a little bit too much over here.

File: CHANGELOG.md [hunk 2]
```diff
@@ -1,4 +1,18 @@
...
+    Tasks with failed dependencies will fail as well.
+- New state `FailedToStart`. Used if the process cannot be started
+- New state `DependencyFailed`. Used if any dependency of a task fails.
+
+**Improvements:**
+- Process log output is no longer stored in memory. This significantly reduced RAM usage for large log outputs.
+- Process log output is compressed in-memory on read from disk. This leads to reduced bandwidth and RAM usage.
+
+**Changes:**
+- Pueue no longer stores log output in it's backup files
```
Comment (sourcefrog) [inline CHANGELOG.md:13]: It's just "it's" for the possessive, analogous to "his" or "hers".

File: client/output.rs [hunk 3]
```diff
@@ -232,27 +239,40 @@ pub fn print_log(task: &Task) {
...
-            println!(
-                "{}",
-                style("Std_out: ")
-                    .with(Color::Green)
-                    .attribute(Attribute::Bold)
-            );
-            println!("{}", stdout);
+    if !task_log.stdout.is_empty() {
+        if let Err(err) = print_task_output(&task_log, true) {
+            println!("Error while parsing stdout: {}", err);
```
Comment (sourcefrog) [inline client/output.rs:244]: Should these be "parsing" or "printing"?

File: client/output.rs [hunk 4]
```diff
@@ -232,27 +239,40 @@ pub fn print_log(task: &Task) {
...
-            println!("{}", stderr);
-        }
+    if !task_log.stderr.is_empty() {
+        if let Err(err) = print_task_output(&task_log, false) {
+            println!("Error while parsing stderr: {}", err);
+        };
     }
 }
+
+/// Pritn the stdout of a finished process
```
Comment (sourcefrog) [inline client/output.rs:255]: *Print

File: client/output.rs [hunk 5]
```diff
@@ -232,27 +239,40 @@ pub fn print_log(task: &Task) {
...
+/// The logs are compressed using Brotli and then encoded to Base64
```
Comment (sourcefrog) [inline client/output.rs:256]: Is it Brotli or Snappy?

File: CHANGELOG.md [hunk 6]
```diff
@@ -1,4 +1,18 @@
-# v0.3.0
+# v0.4.0
```
Comment (sourcefrog) [inline CHANGELOG.md:1]: It seems like new clients will be confused by trying to talk to old servers, with this protocol change. Do you want to add a warning to restart them? Or even some inline marker in the connection?

File: CHANGELOG.md (hunk 2 above)
Comment (sourcefrog) [reply CHANGELOG.md:13]: And (such a tiny nit) some of the lines are missing periods.

File: client/output.rs (hunk 5 above)
Comment (Nukesor) [reply client/output.rs:256]: Snappy. Forgot to change the comment.

Brotli was way to slow

File: client/output.rs (hunk 3 above)
Comment (Nukesor) [reply client/output.rs:244]: That should be parsing. This only occurs if some kind of error during deserialization occurred.

File: daemon/log.rs [hunk 7]
```diff
@@ -63,3 +65,27 @@ pub fn clean_log_handles(task_id: usize, settings: &Settings) {
         );
     };
 }
+
+/// Return stdout and stderr of a finished process
+/// Everything is compressed using Brotli and then encoded to Base64
```
Comment (sourcefrog) [inline daemon/log.rs:70]: Snappy here too?

File: daemon/log.rs [hunk 8]
```diff
@@ -63,3 +65,27 @@ pub fn clean_log_handles(task_id: usize, settings: &Settings) {
...
+pub fn read_and_compress_log_files(
+    task_id: usize,
+    settings: &Settings,
+) -> Result<(Vec<u8>, Vec<u8>)> {
+    let (mut stdout_handle, mut stderr_handle) = match get_log_file_handles(task_id, settings) {
+        Ok((stdout, stderr)) => (stdout, stderr),
+        Err(err) => return Err(anyhow!(format!("Error while opening the output files: {}", err))),
```
Comment (sourcefrog) [inline daemon/log.rs:77]: I think you can use [`bail!()`](https://docs.rs/anyhow/1.0.28/anyhow/macro.bail.html) here

File: daemon/log.rs (hunk 7 above)
Comment (sourcefrog) [inline daemon/log.rs:70]: I haven't followed the logic really closely, but is it actually necessary to base64-encode if you're sending it over bincode? Isn't that binary-safe?

**Comment by Nukesor** [comment]
Thanks for the extensive reviews :) I really appreciate your help!

I'm in the middle of making the whole "logs sent via socket" thingy optional. The new default will be to read the files directly from disk for clients.

I agree that exposing the service adds a strong and powerful attack vector for RCE.
That's why I restricted any communication to loopback for now.

I'm waiting for a fool-proof and easy-to-use low-level tcp crypto-library to pop up.
SSH port forwarding can be used for now as a workaround, but I would love to get this supported natively. (I tried to look around for combining the current solution and SSH inside of Rust, but it doesn't look like there are good libraries out there for this problem yet).

However, I won't implement this, until I'm VERY certain that the underlying crypto is safe (Which will probably take quite some time). It's something I would like to see added to the project and I like to keep it in mind, but I'll try to make it work without it.

Hence, the new feature to read log files locally. You were absolutely right about this :)

**Comment by sourcefrog** [comment]
Thanks! It's been fun working with you on this.

I think the popular thing these days for such situations is mTLS, Mutual TLS. It does still have a challenge of generating and managing keys and access, which needs the user to have some infrastructure and beyond just the library.

Some background reading, but not drop-in solutions for Rust:

* https://cloud.google.com/security/encryption-in-transit/application-layer-transport-security - not literally TLS but similar
* https://smallstep.com/ -- apparently pretty lightweight key management infrastructure - I haven't used it

File: daemon/log.rs (hunk 7 above)
Comment (Nukesor) [reply daemon/log.rs:70]: That was an old comment as well^^
The base64 encode was needed before migrating to bincode, since binary data isn't natively supported in JSON.

File: daemon/log.rs (hunk 8 above)
Comment (Nukesor) [reply daemon/log.rs:77]: Nice. Didn't know about that one!

File: CHANGELOG.md (hunk 6 above)
Comment (Nukesor) [reply CHANGELOG.md:1]: Added

**Comment by Nukesor** [comment]
Ok. I think this can finally be merged into master.

I'll probably run the new master version for a few days on my machines before releasing a new version, though.
